nekromant322/TwitchMentorBot

- src/main/java/com/nekromant/twitch/contoller/PageController.java
- src/main/java/com/nekromant/twitch/contoller/rest/IncomingReviewRestController.java
- src/main/resources/static/incomingReviewWidget.html
- src/main/resources/static/js/incomingReviewWidget.js
Настройка цвета шрифта по параметру color в url запроса (по умолчанию красный цвет).
На прикрепленных скриншотах: слева - старый вариант, справа - новый.
> Added incoming review widget

- src/main/resources/static/pixelEditor.html
- src/main/resources/static/pixelPanel.html
Для избавления ошибок, связанных с отсутствием элемента с определенным id, и для отображения матрицы в панели (/pixel/panel) добавила проверку на соответствие положения пикселя из бд размерам таблицы, но пока только на фронте
> Fixed front for pixelwars

- src/main/java/com/nekromant/twitch/contoller/rest/PixelController.java
- src/main/java/com/nekromant/twitch/dto/TableSizeDTO.java
- src/main/java/com/nekromant/twitch/service/PixelStateService.java
- src/main/resources/application.yml
- src/main/resources/static/pixelEditor.html
- src/main/resources/static/pixelPanel.html
Теперь размеры таблицы зависят от установленных значений в properties.yml, а также теперь не сохранится в бд пиксель, позиция которая не соответствует размерам таблицы, при этом пиксель не спишется с пользователя.
> Added getting table size from properties

- docker-compose.yml
- src/main/resources/application.yml
Добавила экспоуз порт для бд в контейнере, чтобы можно было локально запущенный бот видел бд из контейнера. Соответственно в application.yml прописала хост бд так, чтобы он зависел от того как запущен бот (в контейнере или локально).
> Updated application.yml and docker-compose.yml for local work

- src/main/java/com/nekromant/twitch/command/BoostyCommand.java
- src/main/java/com/nekromant/twitch/command/PixelWarsCommand.java
- src/main/java/com/nekromant/twitch/command/TodayCommand.java
- src/main/java/com/nekromant/twitch/command/TodayUpdateCommand.java
- src/main/java/com/nekromant/twitch/contant/MessageContent.java
- src/main/java/com/nekromant/twitch/content/Message.java
- src/main/java/com/nekromant/twitch/content/MessageContent.java
- src/main/resources/application.yml
> Bot commands

- .github/workflows/deploy.yml
- src/main/java/com/nekromant/twitch/config/SecurityConfig.java
> Crud panel

- pom.xml
- src/main/java/com/nekromant/twitch/aop/LoggingCommands.java
- src/main/java/com/nekromant/twitch/command/BotCommand.java
Был добавлен аспект на логирование вызовов команд в чате на Твич канале
> Added logging for bot commands

- src/main/java/com/nekromant/twitch/command/HelpCommand.java
- src/main/java/com/nekromant/twitch/content/MessageContent.java
Создал класс HelpCommand, добавил две константы в класс MessageContent
> Создание команды !help

- src/main/java/com/nekromant/twitch/service/KindnessService.java
фикс ошибки превышения кол-ва токенов при оценке текста Chat GPT
> Fix Feature/create kindness command

- src/main/java/com/nekromant/twitch/command/BotCommand.java
- src/main/java/com/nekromant/twitch/command/HelpCommand.java
- src/main/java/com/nekromant/twitch/command/TodayCommand.java
- src/main/java/com/nekromant/twitch/command/settings/CustomCommandNamesHolder.java
- src/main/java/com/nekromant/twitch/command/settings/HelpBotCommandBeanPostProcessor.java
- src/main/java/com/nekromant/twitch/content/MessageContent.java
Кастомные команды теперь выводятся автоматически при вызове команды !help.
> Update Feature/edit help comand

- src/main/java/com/nekromant/twitch/service/DonationAlertsService.java
- src/main/java/com/nekromant/twitch/service/KindnessService.java
- src/main/resources/application.yml
Изменена логика обработки ошибки при неуспешном получении донатов от DonationAlerts
> Изменена логика обработки ошибки при неуспешном получении донатов 

- src/main/java/com/nekromant/twitch/service/TwitchCommandTimerService.java
Немного переписал логику. Связал "доверительное время" с периодом вызова CommandSchedule для отправления команд в чат. Это должно сделать логику более безопасной с связанной.
> Устранён баг с не отправлением команд в чат

- .github/workflows/deploy.yml
Ранее была указана учётка первого разработчика. Теперь указана учётка "админа".
> Новый пользователь

- src/main/java/com/nekromant/twitch/exception/NotFoundDonationAlertsTokenException.java
- src/main/java/com/nekromant/twitch/exception/UnauthorizedDonationAlertsTokenException.java
- src/main/java/com/nekromant/twitch/service/DonationAlertsService.java
* Добавлены ошибки при утере или невалидном токене DA
* Изменена логика обработки ошибок
* Добавлена проверка на случай получения пустого токена при успешном запросе
> Добавлены ошибки при утере или невалидном токене DA

- src/main/resources/static/js/songListEditor.js
- src/main/resources/static/js/songListPanel.js
- src/main/resources/static/songListEditor.html
- src/main/resources/static/songListPanel.html
Исправлены пути на относительные в html и js для SongListEditor и SongListPanel
> [songList] пути исправлены на относительные

- src/main/java/com/nekromant/twitch/repository/SongRepository.java
- src/main/java/com/nekromant/twitch/service/SongService.java
Теперь список песен на /editor и /panel отсортирован по исполнителю и названию
> [songList] song list sorting fix

- pom.xml
- src/main/java/com/nekromant/twitch/command/DailyBonusCheckCommand.java
- src/main/java/com/nekromant/twitch/content/MessageContent.java
- src/main/java/com/nekromant/twitch/repository/DailyBonusRepository.java
- src/main/java/com/nekromant/twitch/service/DailyBonusService.java
Теперь при вызове в чате команды !выпито бот помимо количества выпитого смузи показывает место в топе (при одинаковом количестве у разных пользователей сортировка идет по id твича)
Также команду можно использовать следующим образом: !выпито <username>, в таком случае бот ответит данными для указанного пользователя
> [daily bonus feature] обновление функционала команды !выпито

- src/main/java/com/nekromant/twitch/config/SecurityConfig.java
- src/main/java/com/nekromant/twitch/controller/PageController.java
- src/main/java/com/nekromant/twitch/controller/rest/DailyBonusController.java
- src/main/java/com/nekromant/twitch/dto/DailyBonusDTO.java
- src/main/java/com/nekromant/twitch/dto/PointAucObjectDTO.java
- src/main/java/com/nekromant/twitch/mapper/DailyBonusMapper.java
- src/main/java/com/nekromant/twitch/model/DailyBonus.java
- src/main/java/com/nekromant/twitch/repository/DailyBonusRepository.java
- src/main/java/com/nekromant/twitch/service/DailyBonusService.java
- src/main/resources/static/dailyBonusPage.html
- src/main/resources/static/js/dailyBonusPage.js
Добавлена админская страница /dailyBonus с таблицей юзеров и их количеством выпитых смузи. На странице есть кнопка Export, позволяющая выгрузить таблицу в файл с необходимыми для **_pointauc_** данными. Этот файл можно вручную загрузить на **_pointauc_** для  проведения розыгрыша.
> [upgrade daily bonus feature] добавлена админская страница /dailyBonus

- src/main/java/com/nekromant/twitch/command/DailyBonusCheckCommand.java
Теперь верхний регистр в никах не мешает команде !выпито <username>
> [daily bonus feature fix] upper case username fix

- src/main/java/com/nekromant/twitch/config/properties/ScheduleConfigProperties.java
- src/main/java/com/nekromant/twitch/repository/TwitchCommandRepository.java
- src/main/java/com/nekromant/twitch/schedule/CommandSchedule.java
- src/main/java/com/nekromant/twitch/service/TwitchCommandTimerService.java
- src/main/resources/application.yml
Переделана логика вызова команд. <Советую увеличить время шедулда>
> Исправлен баг с вызовом команд ботом

- src/main/java/com/nekromant/twitch/repository/TwitchCommandRepository.java
- src/main/java/com/nekromant/twitch/service/TwitchCommandTimerService.java
- src/main/resources/application.yml
- Переписан sql-запрос к БД.
- Сделана проверка на возможный NPE в коде
- Увеличено время вызова команд до 3-х минут
> Добавлена проверка на NULL в sql-запросе и в фильтрации стрима

- src/main/java/com/nekromant/twitch/command/DailyBonusCommand.java
Теперь !смузи срабатывает только когда стрим онлайн
> [only live daily bonus feature fix]

- src/main/java/com/nekromant/twitch/repository/TwitchCommandRepository.java
- src/main/java/com/nekromant/twitch/service/TwitchCommandTimerService.java
Устранён баг с невыходом команды с null lastCompletionTime
> Избавиться от спама команд

- .github/workflows/deploy.yml
- docker-compose.yml
Исправил на новый хост 195.133.147.161, закоментил удаление env.txt
> изменил хост на новый сервер, оставил сохранение env

- .github/workflows/deploy.yml
Замени - на пробел в deploy docker compose
> Исправил в deploy docker-compose -> docker compose

- .github/workflows/deploy.yml
> Добавил в деплой sudo для операций с докер

- .github/workflows/deploy.yml
- docker-compose.yml
Вернул удаление twitch-env.txt через sudo, вернул в докер-композ часть, касающуюся самого приложения
> Вернул в исходное, но с новым сервом

- src/main/java/com/nekromant/twitch/config/SecurityConfig.java
Добавил noop пасс энкодер, чтоб пасс не шифровался
> добавил NoopPassword encoder

- .github/workflows/deploy.yml
- docker-compose.yml
Добавил чат бот сторонний, поменяли образ и креды на nekromant322
> Добавил чат бот сторонний, поменяли образ и креды на nekromant322

- src/main/java/com/nekromant/twitch/service/ResponseService.java
Добавил обновление таймера команд после ручного вызова
> Добавил обновление таймера команд после ручного вызова
